/**
 * Demo catalogue for JIS Beauty & Fashion.
 *
 * Replace/extend these entries with real products, or manage products from the
 * admin dashboard (/admin/products). Images point to placeholder renders in
 * /public/images/products — swap them for real product photography later.
 */
import type { ProductGender } from "@/db/schema";

export type SeedCategory = {
  name: string;
  slug: string;
  description: string;
  image: string;
  sortOrder: number;
};

export type SeedProduct = {
  name: string;
  brand: string;
  category: string; // category slug
  gender: ProductGender;
  price: number;
  salePrice?: number;
  stock: number;
  volume: string;
  fragranceType: string;
  topNotes: string;
  heartNotes: string;
  baseNotes: string;
  longevity: string;
  occasion: string;
  shortDescription: string;
  description: string;
  images: string[];
  isBestSeller?: boolean;
  isNewArrival?: boolean;
  isFeatured?: boolean;
  variants?: { name: string; price: number; salePrice?: number; stock: number }[];
};

export const seedCategories: SeedCategory[] = [
  {
    name: "Perfumes for Women",
    slug: "women",
    description: "Floral, sweet and sophisticated fragrances made to leave a lasting impression.",
    image: "/images/products/women-1.jpg",
    sortOrder: 1,
  },
  {
    name: "Perfumes for Men",
    slug: "men",
    description: "Bold woods, fresh citrus and deep amber scents for the modern gentleman.",
    image: "/images/products/men-1.jpg",
    sortOrder: 2,
  },
  {
    name: "Unisex Perfumes",
    slug: "unisex",
    description: "Genderless compositions built around clean woods, resins and rare florals.",
    image: "/images/products/unisex-1.jpg",
    sortOrder: 3,
  },
  {
    name: "Kids' Fragrances",
    slug: "kids",
    description: "Gentle, alcohol-light scents formulated for delicate skin and little noses.",
    image: "/images/products/kids-1.jpg",
    sortOrder: 4,
  },
  {
    name: "Perfume Oils",
    slug: "perfume-oils",
    description: "Concentrated, long-lasting oils — from classic oud to soft musks.",
    image: "/images/products/oil-1.jpg",
    sortOrder: 5,
  },
];

export const seedBrands = [
  "Maison JIS",
  "Noir Lagos",
  "Ọ̀run Atelier",
  "Velvet & Co.",
  "Amber Route",
  "Sahara Oud",
  "Petit Monde",
];

const W = ["/images/products/women-1.jpg", "/images/products/women-2.jpg"];
const W2 = ["/images/products/women-2.jpg", "/images/products/women-1.jpg"];
const M = ["/images/products/men-1.jpg", "/images/products/men-2.jpg"];
const M2 = ["/images/products/men-2.jpg", "/images/products/men-1.jpg"];
const U = ["/images/products/unisex-1.jpg", "/images/products/men-2.jpg"];
const K = ["/images/products/kids-1.jpg", "/images/products/unisex-1.jpg"];
const O = ["/images/products/oil-1.jpg", "/images/products/oil-2.jpg"];
const O2 = ["/images/products/oil-2.jpg", "/images/products/oil-1.jpg"];

export const seedProducts: SeedProduct[] = [
  /* ------------------------------ WOMEN (10) ------------------------------ */
  {
    name: "Velvet Bloom",
    brand: "Maison JIS",
    category: "women",
    gender: "women",
    price: 38500,
    stock: 24,
    volume: "100ml",
    fragranceType: "Eau de Parfum",
    topNotes: "Bergamot, Pink Pepper, Pear",
    heartNotes: "Peony, Turkish Rose, Jasmine Sambac",
    baseNotes: "White Musk, Sandalwood, Vanilla",
    longevity: "8 – 10 hours",
    occasion: "Everyday, Office, Date Night",
    shortDescription: "A soft rose-peony bouquet wrapped in creamy musk.",
    description:
      "Velvet Bloom opens with a sparkle of bergamot and juicy pear before settling into a lush heart of peony and Turkish rose. A base of white musk and sandalwood keeps it velvety and close to the skin, making it an effortless signature scent from morning meetings to evening dinners.",
    images: W,
    isBestSeller: true,
    isFeatured: true,
  },
  {
    name: "Lagos Nights",
    brand: "Noir Lagos",
    category: "women",
    gender: "women",
    price: 52000,
    salePrice: 45900,
    stock: 15,
    volume: "90ml",
    fragranceType: "Eau de Parfum",
    topNotes: "Blackcurrant, Mandarin, Saffron",
    heartNotes: "Tuberose, Orange Blossom, Praline",
    baseNotes: "Tonka Bean, Amber, Patchouli",
    longevity: "10 – 12 hours",
    occasion: "Evening, Parties, Special Occasions",
    shortDescription: "A warm, addictive gourmand for nights that don’t end early.",
    description:
      "Inspired by the energy of Victoria Island after dark, Lagos Nights pairs sultry tuberose with caramelised praline and a saffron-tinted opening. It dries down to a rich amber-tonka trail that lingers on clothes till morning.",
    images: W2,
    isBestSeller: true,
  },
  {
    name: "Ivory Silk",
    brand: "Maison JIS",
    category: "women",
    gender: "women",
    price: 34000,
    stock: 30,
    volume: "75ml",
    fragranceType: "Eau de Parfum",
    topNotes: "White Peach, Freesia",
    heartNotes: "Magnolia, Lily of the Valley, Iris",
    baseNotes: "Cashmere Wood, Soft Musk",
    longevity: "6 – 8 hours",
    occasion: "Daytime, Office, Brunch",
    shortDescription: "Clean white florals with a powdery cashmere finish.",
    description:
      "Ivory Silk is the scent of freshly pressed linen and a bouquet of white flowers. Magnolia and iris give it a polished, powdery elegance that feels refined without ever being loud.",
    images: W,
  },
  {
    name: "Rose Ọba",
    brand: "Ọ̀run Atelier",
    category: "women",
    gender: "women",
    price: 61000,
    stock: 12,
    volume: "100ml",
    fragranceType: "Extrait de Parfum",
    topNotes: "Damask Rose, Raspberry, Pink Pepper",
    heartNotes: "Rose Absolute, Geranium, Oud",
    baseNotes: "Agarwood, Amber, Musk",
    longevity: "12+ hours",
    occasion: "Weddings, Evening, Owambe",
    shortDescription: "A regal rose-oud extrait for statement moments.",
    description:
      "Rose Ọba layers three expressions of rose over a smoky oud heart. Dark raspberry and pink pepper keep the opening lively, while amber and agarwood give it the depth of a true occasion fragrance.",
    images: W2,
    isNewArrival: true,
    isFeatured: true,
  },
  {
    name: "Sugar Orchid",
    brand: "Velvet & Co.",
    category: "women",
    gender: "women",
    price: 29500,
    salePrice: 24900,
    stock: 40,
    volume: "100ml",
    fragranceType: "Eau de Parfum",
    topNotes: "Lychee, Bergamot",
    heartNotes: "Orchid, Coconut Cream, Heliotrope",
    baseNotes: "Vanilla, Sugar Cane, Musk",
    longevity: "7 – 9 hours",
    occasion: "Everyday, Casual, Weekend",
    shortDescription: "Sweet tropical orchid with a creamy vanilla base.",
    description:
      "Playful and comforting, Sugar Orchid blends lychee and coconut cream with a soft sugared vanilla. It is the easy-to-wear sweet scent that earns compliments without trying.",
    images: W,
  },
  {
    name: "Golden Hour",
    brand: "Maison JIS",
    category: "women",
    gender: "women",
    price: 42000,
    stock: 18,
    volume: "100ml",
    fragranceType: "Eau de Parfum",
    topNotes: "Mandarin, Fig Leaf, Cardamom",
    heartNotes: "Orange Blossom, Ylang-Ylang, Honey",
    baseNotes: "Amber, Benzoin, Vetiver",
    longevity: "8 – 10 hours",
    occasion: "Sunset Events, Dinner, Travel",
    shortDescription: "Honeyed orange blossom that glows like late-afternoon light.",
    description:
      "Golden Hour captures that warm, hazy moment before sunset. Spiced mandarin opens onto a honeyed orange-blossom heart and finishes in a smooth amber-benzoin glow. Available in two sizes.",
    images: W2,
    isFeatured: true,
    variants: [
      { name: "50ml", price: 26500, stock: 20 },
      { name: "100ml", price: 42000, stock: 18 },
    ],
  },
  {
    name: "Jasmine Reverie",
    brand: "Velvet & Co.",
    category: "women",
    gender: "women",
    price: 31000,
    stock: 22,
    volume: "80ml",
    fragranceType: "Eau de Toilette",
    topNotes: "Green Mandarin, Neroli",
    heartNotes: "Jasmine Grandiflorum, Gardenia",
    baseNotes: "Sandalwood, Ambrette",
    longevity: "5 – 7 hours",
    occasion: "Daytime, Spring, Casual",
    shortDescription: "An airy jasmine that feels like fresh flowers by an open window.",
    description:
      "Jasmine Reverie is a bright, natural take on the queen of flowers. Neroli and green mandarin lift the jasmine, and a whisper of sandalwood keeps it soft and skin-like.",
    images: W,
  },
  {
    name: "Amber Crush",
    brand: "Amber Route",
    category: "women",
    gender: "women",
    price: 47500,
    stock: 20,
    volume: "100ml",
    fragranceType: "Eau de Parfum",
    topNotes: "Cinnamon, Red Apple, Bergamot",
    heartNotes: "Rose, Amber Accord, Labdanum",
    baseNotes: "Vanilla, Sandalwood, Tonka",
    longevity: "10 – 12 hours",
    occasion: "Evening, Harmattan Season, Date Night",
    shortDescription: "Spiced amber and rose with serious staying power.",
    description:
      "Amber Crush is a warm hug of cinnamon-dusted apple over rose and resinous amber. One of our most complimented scents, it performs beautifully in cooler evenings and harmattan air.",
    images: W2,
    isBestSeller: true,
  },
  {
    name: "Pearl Musk",
    brand: "Maison JIS",
    category: "women",
    gender: "women",
    price: 36000,
    stock: 26,
    volume: "100ml",
    fragranceType: "Eau de Parfum",
    topNotes: "Aldehydes, Pear Blossom",
    heartNotes: "Iris, Violet, Rose Water",
    baseNotes: "White Musk, Ambrette, Cedar",
    longevity: "7 – 9 hours",
    occasion: "Office, Everyday, Church",
    shortDescription: "A clean, luminous musk that smells like expensive skin.",
    description:
      "Pearl Musk is quiet luxury in a bottle: soft aldehydes, powdery iris and a radiant white musk. It stays close, polished and impeccably clean all day.",
    images: W,
  },
  {
    name: "Blush Noir",
    brand: "Noir Lagos",
    category: "women",
    gender: "women",
    price: 58000,
    stock: 10,
    volume: "100ml",
    fragranceType: "Eau de Parfum",
    topNotes: "Black Cherry, Bitter Almond, Plum",
    heartNotes: "Rose, Black Orchid, Cacao",
    baseNotes: "Vanilla Bourbon, Oud, Patchouli",
    longevity: "10 – 12 hours",
    occasion: "Evening, Winter Travel, Nightlife",
    shortDescription: "Dark cherry and cacao over a smoky vanilla-oud base.",
    description:
      "Blush Noir is seductive and a little mysterious — a boozy black cherry opening leads to a heart of dark orchid and cacao, before oud and bourbon vanilla settle in for the night.",
    images: W2,
    isNewArrival: true,
  },

  /* ------------------------------- MEN (10) ------------------------------- */
  {
    name: "Noir Intense",
    brand: "Noir Lagos",
    category: "men",
    gender: "men",
    price: 55000,
    stock: 20,
    volume: "100ml",
    fragranceType: "Eau de Parfum",
    topNotes: "Bergamot, Black Pepper, Cardamom",
    heartNotes: "Lavender, Iris, Amberwood",
    baseNotes: "Vanilla, Tonka Bean, Cedar",
    longevity: "10 – 12 hours",
    occasion: "Evening, Date Night, Events",
    shortDescription: "A magnetic amber-vanilla with a spicy edge.",
    description:
      "Noir Intense is the fragrance men keep re-buying. Peppery citrus and lavender give way to a deep, warm amberwood and vanilla drydown that projects confidently without shouting.",
    images: M,
    isBestSeller: true,
    isFeatured: true,
  },
  {
    name: "Ọba Leather",
    brand: "Ọ̀run Atelier",
    category: "men",
    gender: "men",
    price: 68000,
    stock: 9,
    volume: "100ml",
    fragranceType: "Extrait de Parfum",
    topNotes: "Saffron, Bergamot, Nutmeg",
    heartNotes: "Leather, Oud, Violet Leaf",
    baseNotes: "Vetiver, Amber, Birch Tar",
    longevity: "12+ hours",
    occasion: "Formal, Boardroom, Traditional Events",
    shortDescription: "Smoky saffron leather for the man in charge.",
    description:
      "Ọba Leather is a rich, regal composition of saffron-spiced leather and smoky oud. Dry, powerful and long-lasting — built for agbada, tailored suits and rooms where you are meant to be noticed.",
    images: M2,
    isFeatured: true,
  },
  {
    name: "Atlantic Blue",
    brand: "Maison JIS",
    category: "men",
    gender: "men",
    price: 39900,
    salePrice: 34900,
    stock: 35,
    volume: "100ml",
    fragranceType: "Eau de Toilette",
    topNotes: "Grapefruit, Sea Salt, Mint",
    heartNotes: "Marine Accord, Sage, Geranium",
    baseNotes: "Ambergris, Driftwood, Musk",
    longevity: "6 – 8 hours",
    occasion: "Daytime, Office, Sports",
    shortDescription: "A fresh aquatic that smells like a Lagos beach morning.",
    description:
      "Atlantic Blue is crisp and energising: salty grapefruit and mint over a clean marine heart, drying down to warm ambergris and driftwood. Perfect for hot afternoons and the office.",
    images: M2,
    isBestSeller: true,
  },
  {
    name: "Cedar & Smoke",
    brand: "Velvet & Co.",
    category: "men",
    gender: "men",
    price: 44000,
    stock: 16,
    volume: "100ml",
    fragranceType: "Eau de Parfum",
    topNotes: "Pink Pepper, Elemi",
    heartNotes: "Cedarwood, Incense, Cypress",
    baseNotes: "Guaiac Wood, Smoked Vanilla",
    longevity: "8 – 10 hours",
    occasion: "Evening, Autumn Travel, Casual",
    shortDescription: "Dry cedar and soft incense with a smoked-vanilla base.",
    description:
      "Cedar & Smoke is a modern woody fragrance built on pencil-shaving cedar and church incense, softened by a lightly smoked vanilla. Understated, masculine and quietly addictive.",
    images: M,
  },
  {
    name: "Sahara Oud Homme",
    brand: "Sahara Oud",
    category: "men",
    gender: "men",
    price: 72000,
    stock: 8,
    volume: "90ml",
    fragranceType: "Eau de Parfum",
    topNotes: "Cardamom, Rose, Saffron",
    heartNotes: "Cambodian Oud, Patchouli",
    baseNotes: "Sandalwood, Amber, Musk",
    longevity: "12+ hours",
    occasion: "Special Occasions, Evening, Eid",
    shortDescription: "A true oud built for those who understand oud.",
    description:
      "Sahara Oud Homme is an uncompromising oud: animalic, resinous and smooth all at once. Cardamom and rose brighten the opening, and the drydown is a plush sandalwood-amber that lasts through the next day.",
    images: M2,
    isNewArrival: true,
  },
  {
    name: "Midnight Vetiver",
    brand: "Maison JIS",
    category: "men",
    gender: "men",
    price: 41000,
    stock: 21,
    volume: "100ml",
    fragranceType: "Eau de Parfum",
    topNotes: "Lemon Zest, Ginger",
    heartNotes: "Haitian Vetiver, Nutmeg, Clary Sage",
    baseNotes: "Vetiver Root, Tobacco, Oakmoss",
    longevity: "8 – 10 hours",
    occasion: "Office, Evening, Everyday",
    shortDescription: "An earthy, elegant vetiver with a tobacco finish.",
    description:
      "Midnight Vetiver takes classic Haitian vetiver and gives it a darker, more refined edge with tobacco leaf and oakmoss. Sophisticated enough for the boardroom, warm enough for dinner.",
    images: M,
  },
  {
    name: "Iron Citrus",
    brand: "Velvet & Co.",
    category: "men",
    gender: "men",
    price: 33500,
    stock: 28,
    volume: "100ml",
    fragranceType: "Eau de Toilette",
    topNotes: "Sicilian Lemon, Bergamot, Basil",
    heartNotes: "Juniper, Lavender, Metallic Accord",
    baseNotes: "Vetiver, Musk, Cedar",
    longevity: "5 – 7 hours",
    occasion: "Daytime, Gym, Casual",
    shortDescription: "Zesty citrus with a cool metallic twist.",
    description:
      "Iron Citrus is bright, sharp and clean — Sicilian lemon and basil with a cool steel-like accord, grounded by vetiver and cedar. Your go-to for hot days and post-gym freshness.",
    images: M2,
  },
  {
    name: "Ebony Spice",
    brand: "Amber Route",
    category: "men",
    gender: "men",
    price: 49000,
    stock: 17,
    volume: "100ml",
    fragranceType: "Eau de Parfum",
    topNotes: "Cinnamon, Clove, Orange Peel",
    heartNotes: "Ebony Wood, Tobacco Flower, Rum",
    baseNotes: "Amber, Benzoin, Vanilla",
    longevity: "10 – 12 hours",
    occasion: "Evening, Harmattan, Celebrations",
    shortDescription: "Rum-soaked spices over dark wood and amber.",
    description:
      "Ebony Spice is a warm, boozy oriental — cinnamon and clove soaked in dark rum, resting on ebony wood and glowing amber. Made for cool nights and celebrations.",
    images: M,
    isBestSeller: true,
  },
  {
    name: "Harmattan",
    brand: "Ọ̀run Atelier",
    category: "men",
    gender: "men",
    price: 57500,
    salePrice: 51000,
    stock: 14,
    volume: "100ml",
    fragranceType: "Eau de Parfum",
    topNotes: "Dry Ginger, Bergamot, Sand Accord",
    heartNotes: "Frankincense, Cypriol, Papyrus",
    baseNotes: "Dry Amber, Cedar, Musk",
    longevity: "9 – 11 hours",
    occasion: "Everyday, Travel, Evening",
    shortDescription: "Dusty frankincense and papyrus — the season in a bottle.",
    description:
      "Harmattan evokes the dry northern wind: dusty ginger, frankincense smoke and papyrus over a warm mineral amber. Unusual, addictive and distinctly Nigerian in spirit.",
    images: M2,
    isNewArrival: true,
  },
  {
    name: "Tobacco Honey",
    brand: "Noir Lagos",
    category: "men",
    gender: "men",
    price: 62000,
    stock: 11,
    volume: "100ml",
    fragranceType: "Eau de Parfum",
    topNotes: "Honey, Cognac, Pink Pepper",
    heartNotes: "Tobacco Leaf, Cacao, Dried Fruits",
    baseNotes: "Vanilla, Tonka, Labdanum",
    longevity: "12+ hours",
    occasion: "Evening, Nightlife, Winter Travel",
    shortDescription: "Sweet tobacco and cognac with a lush vanilla base.",
    description:
      "Tobacco Honey is decadent: honeyed cognac poured over sweet pipe tobacco and cacao. A commanding beast-mode scent that lasts and lasts.",
    images: M,
  },

  /* ------------------------------ UNISEX (5) ------------------------------ */
  {
    name: "Santal Stone",
    brand: "Maison JIS",
    category: "unisex",
    gender: "unisex",
    price: 46000,
    stock: 25,
    volume: "100ml",
    fragranceType: "Eau de Parfum",
    topNotes: "Cardamom, Iris, Violet",
    heartNotes: "Australian Sandalwood, Papyrus, Ambrox",
    baseNotes: "Leather, Cedar, Musk",
    longevity: "8 – 10 hours",
    occasion: "Everyday, Office, Evening",
    shortDescription: "Creamy sandalwood with a soft leather edge.",
    description:
      "Santal Stone is a minimalist, milky sandalwood with iris and a hint of leather. Effortlessly unisex and universally complimented — our answer to the modern signature scent.",
    images: U,
    isBestSeller: true,
    isFeatured: true,
  },
  {
    name: "Oud Royale",
    brand: "Sahara Oud",
    category: "unisex",
    gender: "unisex",
    price: 85000,
    stock: 6,
    volume: "100ml",
    fragranceType: "Extrait de Parfum",
    topNotes: "Saffron, Bulgarian Rose",
    heartNotes: "Laotian Oud, Amber, Praline",
    baseNotes: "Sandalwood, Musk, Vanilla",
    longevity: "12+ hours",
    occasion: "Weddings, Formal, Gifting",
    shortDescription: "Our most luxurious oud — rose, saffron and sweet resins.",
    description:
      "Oud Royale is an opulent, sweetened oud that sits comfortably on anyone. Saffron and rose glimmer over a rich agarwood heart with a soft praline-amber finish. The ultimate gift.",
    images: U,
    isFeatured: true,
  },
  {
    name: "White Tea & Fig",
    brand: "Velvet & Co.",
    category: "unisex",
    gender: "unisex",
    price: 37000,
    stock: 30,
    volume: "100ml",
    fragranceType: "Eau de Toilette",
    topNotes: "Fig Leaf, Bergamot, Green Tea",
    heartNotes: "White Tea, Fig Milk, Jasmine",
    baseNotes: "Cedar, Coconut Wood, Musk",
    longevity: "5 – 7 hours",
    occasion: "Daytime, Brunch, Home Fragrance",
    shortDescription: "Green fig and clean white tea — fresh, calm, effortless.",
    description:
      "White Tea & Fig is a serene green scent: milky fig leaf and delicate white tea on a soft cedar base. Light enough for the hottest afternoon, refined enough for any occasion.",
    images: U,
    isNewArrival: true,
  },
  {
    name: "Neroli Sun",
    brand: "Maison JIS",
    category: "unisex",
    gender: "unisex",
    price: 39000,
    stock: 22,
    volume: "100ml",
    fragranceType: "Eau de Parfum",
    topNotes: "Neroli, Petitgrain, Lemon",
    heartNotes: "Orange Blossom, Honeysuckle",
    baseNotes: "White Musk, Amber, Vetiver",
    longevity: "6 – 8 hours",
    occasion: "Daytime, Travel, Weekend",
    shortDescription: "Sun-warmed orange blossom with a clean musky trail.",
    description:
      "Neroli Sun is bottled sunshine — radiant neroli and honeysuckle over a soft amber-musk. A joyful, easy scent to share with whoever you love.",
    images: U,
  },
  {
    name: "Black Amber",
    brand: "Amber Route",
    category: "unisex",
    gender: "unisex",
    price: 53000,
    salePrice: 47500,
    stock: 13,
    volume: "100ml",
    fragranceType: "Eau de Parfum",
    topNotes: "Black Pepper, Bergamot, Incense",
    heartNotes: "Amber, Labdanum, Rose",
    baseNotes: "Oud, Vanilla, Patchouli",
    longevity: "10 – 12 hours",
    occasion: "Evening, Events, Cool Weather",
    shortDescription: "A dark resinous amber with smoky incense.",
    description:
      "Black Amber is deep, smoky and enveloping — incense-laced amber and labdanum with a touch of rose, drying down to smooth oud and vanilla. Perfect for evenings and gifting.",
    images: U,
  },

  /* ------------------------------- KIDS (5) ------------------------------- */
  {
    name: "Little Cloud",
    brand: "Petit Monde",
    category: "kids",
    gender: "kids",
    price: 12500,
    stock: 40,
    volume: "50ml",
    fragranceType: "Alcohol-Free Body Mist",
    topNotes: "Cotton Flower, Pear",
    heartNotes: "Baby Powder Accord, Chamomile",
    baseNotes: "Soft Musk, Vanilla",
    longevity: "3 – 4 hours",
    occasion: "Everyday, School, Bedtime",
    shortDescription: "A powdery-soft, alcohol-free mist for little ones.",
    description:
      "Little Cloud is a gentle, dermatologist-tested mist with a cosy cotton-and-chamomile scent. Alcohol-free and formulated for delicate skin — perfect after bath time.",
    images: K,
    isBestSeller: true,
  },
  {
    name: "Sunny Berry",
    brand: "Petit Monde",
    category: "kids",
    gender: "kids",
    price: 11900,
    stock: 35,
    volume: "50ml",
    fragranceType: "Alcohol-Free Body Mist",
    topNotes: "Strawberry, Raspberry",
    heartNotes: "Peach Blossom, Vanilla Cream",
    baseNotes: "Soft Musk",
    longevity: "3 – 4 hours",
    occasion: "Everyday, Parties, Playdates",
    shortDescription: "Bright, fruity and fun — a berry scent kids adore.",
    description:
      "Sunny Berry is a juicy strawberry-raspberry mist with a creamy vanilla heart. Gentle, alcohol-free and sized for small hands.",
    images: K,
  },
  {
    name: "Cotton Hug",
    brand: "Petit Monde",
    category: "kids",
    gender: "kids",
    price: 13500,
    salePrice: 11500,
    stock: 30,
    volume: "50ml",
    fragranceType: "Alcohol-Free Body Mist",
    topNotes: "Clean Linen Accord, Mandarin",
    heartNotes: "Lavender, Cotton Flower",
    baseNotes: "White Musk, Sandalwood",
    longevity: "3 – 5 hours",
    occasion: "Everyday, Bedtime, Travel",
    shortDescription: "Calming lavender and fresh linen for bedtime routines.",
    description:
      "Cotton Hug smells like freshly washed pyjamas. A calming lavender-linen blend designed to settle little ones down at the end of the day.",
    images: K,
  },
  {
    name: "Vanilla Giggles",
    brand: "Petit Monde",
    category: "kids",
    gender: "kids",
    price: 12000,
    stock: 32,
    volume: "50ml",
    fragranceType: "Alcohol-Free Body Mist",
    topNotes: "Caramel, Banana Cream",
    heartNotes: "Vanilla Orchid, Coconut",
    baseNotes: "Tonka Bean, Musk",
    longevity: "3 – 4 hours",
    occasion: "Everyday, Parties, Weekend",
    shortDescription: "A sweet vanilla-caramel treat, no sugar rush required.",
    description:
      "Vanilla Giggles is a warm, dessert-like scent of vanilla and gentle caramel that kids love. Gentle, alcohol-free and safe for daily wear.",
    images: K,
    isNewArrival: true,
  },
  {
    name: "Ocean Splash Kids",
    brand: "Petit Monde",
    category: "kids",
    gender: "kids",
    price: 12900,
    stock: 28,
    volume: "50ml",
    fragranceType: "Alcohol-Free Body Mist",
    topNotes: "Green Apple, Sea Breeze",
    heartNotes: "Water Lily, Mint Leaf",
    baseNotes: "Light Musk, Cedar",
    longevity: "3 – 4 hours",
    occasion: "Everyday, School, Sports",
    shortDescription: "A fresh, sporty scent for active boys and girls.",
    description:
      "Ocean Splash Kids is crisp green apple and cool sea breeze — clean, fresh and energising for school days and football practice.",
    images: K,
  },

  /* --------------------------- PERFUME OILS (10) -------------------------- */
  {
    name: "Oud Ọba Oil",
    brand: "Sahara Oud",
    category: "perfume-oils",
    gender: "unisex",
    price: 18000,
    stock: 45,
    volume: "12ml",
    fragranceType: "Perfume Oil (Roll-On)",
    topNotes: "Saffron, Rose",
    heartNotes: "Cambodian Oud, Amber",
    baseNotes: "Sandalwood, Musk",
    longevity: "12+ hours",
    occasion: "Everyday, Prayer, Events",
    shortDescription: "Concentrated oud oil — a drop lasts all day.",
    description:
      "Oud Ọba Oil is a high-concentration roll-on of smooth Cambodian oud with rose and saffron. Alcohol-free, skin-safe and extraordinarily long lasting. Available in 6ml and 12ml.",
    images: O,
    isBestSeller: true,
    isFeatured: true,
    variants: [
      { name: "6ml", price: 9500, stock: 50 },
      { name: "12ml", price: 18000, stock: 45 },
    ],
  },
  {
    name: "Musk Tahara",
    brand: "Sahara Oud",
    category: "perfume-oils",
    gender: "unisex",
    price: 9500,
    stock: 60,
    volume: "12ml",
    fragranceType: "Perfume Oil (Roll-On)",
    topNotes: "Clean Aldehydes",
    heartNotes: "White Musk, Lily",
    baseNotes: "Powdery Musk, Amber",
    longevity: "8 – 10 hours",
    occasion: "Everyday, Layering, Bedtime",
    shortDescription: "The classic clean white musk — soft, pure and versatile.",
    description:
      "Musk Tahara is the beloved clean musk oil: soft, powdery and impeccably fresh. Wear it alone or layer it under any perfume to add longevity and softness.",
    images: O2,
  },
  {
    name: "Amber Rose Oil",
    brand: "Amber Route",
    category: "perfume-oils",
    gender: "women",
    price: 14000,
    salePrice: 12000,
    stock: 38,
    volume: "12ml",
    fragranceType: "Perfume Oil (Roll-On)",
    topNotes: "Rose Petals, Pink Pepper",
    heartNotes: "Amber, Turkish Rose",
    baseNotes: "Vanilla, Benzoin",
    longevity: "10 – 12 hours",
    occasion: "Everyday, Evening, Gifting",
    shortDescription: "Warm amber and rose in a purse-friendly roll-on.",
    description:
      "Amber Rose Oil is a rich, honeyed rose wrapped in warm amber resins. Concentrated, alcohol-free and perfect for topping up through the day.",
    images: O,
  },
  {
    name: "Vanilla Noir Oil",
    brand: "Noir Lagos",
    category: "perfume-oils",
    gender: "unisex",
    price: 15500,
    stock: 30,
    volume: "12ml",
    fragranceType: "Perfume Oil (Roll-On)",
    topNotes: "Black Pepper, Rum",
    heartNotes: "Madagascar Vanilla, Tobacco",
    baseNotes: "Tonka, Oud",
    longevity: "12+ hours",
    occasion: "Evening, Nightlife, Cool Weather",
    shortDescription: "A dark, smoky vanilla oil with rum and tobacco.",
    description:
      "Vanilla Noir Oil turns vanilla grown-up: dark, boozy and smoked with tobacco and a hint of oud. Wear it alone or layer over Noir Intense for a signature trail.",
    images: O2,
  },
  {
    name: "Sandal Cream Oil",
    brand: "Maison JIS",
    category: "perfume-oils",
    gender: "unisex",
    price: 13000,
    stock: 34,
    volume: "12ml",
    fragranceType: "Perfume Oil (Roll-On)",
    topNotes: "Cardamom, Milk Accord",
    heartNotes: "Mysore Sandalwood, Iris",
    baseNotes: "Tonka, Musk",
    longevity: "8 – 10 hours",
    occasion: "Everyday, Office, Layering",
    shortDescription: "Milky sandalwood — creamy, calm and skin-close.",
    description:
      "Sandal Cream Oil is a smooth, milky sandalwood with soft iris and cardamom. Subtle and comforting, it is a favourite for everyday wear and layering.",
    images: O,
    isNewArrival: true,
  },
  {
    name: "Black Oud Oil",
    brand: "Sahara Oud",
    category: "perfume-oils",
    gender: "men",
    price: 21000,
    stock: 20,
    volume: "12ml",
    fragranceType: "Perfume Oil (Roll-On)",
    topNotes: "Smoke, Leather",
    heartNotes: "Black Oud, Patchouli",
    baseNotes: "Labdanum, Vetiver",
    longevity: "12+ hours",
    occasion: "Evening, Traditional Events, Formal",
    shortDescription: "Intense, smoky black oud for serious oud lovers.",
    description:
      "Black Oud Oil is uncompromising: dark, smoky agarwood with leather and earthy patchouli. A little goes a very long way.",
    images: O2,
  },
  {
    name: "Jasmine Petal Oil",
    brand: "Velvet & Co.",
    category: "perfume-oils",
    gender: "women",
    price: 11500,
    stock: 42,
    volume: "12ml",
    fragranceType: "Perfume Oil (Roll-On)",
    topNotes: "Green Leaves, Bergamot",
    heartNotes: "Jasmine Sambac, Tuberose",
    baseNotes: "Sandalwood, Musk",
    longevity: "7 – 9 hours",
    occasion: "Daytime, Everyday, Layering",
    shortDescription: "A fresh, natural jasmine in concentrated oil form.",
    description:
      "Jasmine Petal Oil captures the heady sweetness of night-blooming jasmine, softened with sandalwood. Roll on pulse points for an intimate floral aura.",
    images: O,
  },
  {
    name: "Sweet Musk Oil",
    brand: "Maison JIS",
    category: "perfume-oils",
    gender: "unisex",
    price: 9900,
    stock: 55,
    volume: "12ml",
    fragranceType: "Perfume Oil (Roll-On)",
    topNotes: "Sugared Citrus",
    heartNotes: "Musk, Heliotrope, Vanilla",
    baseNotes: "Amber, Tonka",
    longevity: "8 – 10 hours",
    occasion: "Everyday, Layering, Gifting",
    shortDescription: "A cosy, sweet musk that everyone loves.",
    description:
      "Sweet Musk Oil is warm, powdery and slightly sugary — the comforting musk that gets asked about constantly. Great value and a perfect starter oil.",
    images: O2,
    isBestSeller: true,
  },
  {
    name: "Saffron Amber Oil",
    brand: "Amber Route",
    category: "perfume-oils",
    gender: "unisex",
    price: 19500,
    stock: 18,
    volume: "12ml",
    fragranceType: "Perfume Oil (Roll-On)",
    topNotes: "Saffron, Cinnamon",
    heartNotes: "Amber, Dried Fruits, Rose",
    baseNotes: "Oud, Vanilla, Benzoin",
    longevity: "12+ hours",
    occasion: "Evening, Celebrations, Gifting",
    shortDescription: "Golden saffron and amber — luxurious and long-lasting.",
    description:
      "Saffron Amber Oil is a jewel-toned blend of leathery saffron, dried fruits and glowing amber resins. Rich, warm and radiant for special evenings.",
    images: O,
    isNewArrival: true,
  },
  {
    name: "Coconut Vanilla Oil",
    brand: "Velvet & Co.",
    category: "perfume-oils",
    gender: "women",
    price: 10500,
    stock: 48,
    volume: "12ml",
    fragranceType: "Perfume Oil (Roll-On)",
    topNotes: "Fresh Coconut, Lime",
    heartNotes: "Vanilla Orchid, Tiare Flower",
    baseNotes: "Creamy Musk, Tonka",
    longevity: "7 – 9 hours",
    occasion: "Daytime, Weekend, Vacation",
    shortDescription: "Creamy coconut and vanilla — a holiday on your wrist.",
    description:
      "Coconut Vanilla Oil is a tropical, creamy blend of coconut milk, tiare flower and soft vanilla. Sunny, sweet and irresistibly cosy.",
    images: O2,
  },
];

/** Demo customers used for seeded reviews (password: Customer@2024). */
export const seedCustomers = [
  { firstName: "Adaeze", lastName: "Okafor", email: "adaeze@example.com" },
  { firstName: "Tunde", lastName: "Bakare", email: "tunde@example.com" },
  { firstName: "Chiamaka", lastName: "Nwosu", email: "chiamaka@example.com" },
  { firstName: "Ibrahim", lastName: "Musa", email: "ibrahim@example.com" },
];

export const seedReviewPool = [
  { rating: 5, title: "Absolutely gorgeous", comment: "Smells even better than described. I got compliments at work the very first day. Delivery to Lekki was quick too." },
  { rating: 5, title: "My new signature", comment: "Long-lasting and not overpowering. The bottle looks premium on my dresser. Will definitely repurchase." },
  { rating: 4, title: "Lovely scent", comment: "Beautiful fragrance, projection is moderate which I actually prefer. Packaging was very neat." },
  { rating: 5, title: "Worth every naira", comment: "Ordered on Monday, received on Wednesday in Abuja. Scent lasts through the whole day — 10/10." },
  { rating: 4, title: "Great for the price", comment: "Very nice and authentic. Wish it came in a bigger size but the performance is solid." },
  { rating: 5, title: "Perfect gift", comment: "Bought this for my husband and he hasn't stopped wearing it. JIS customer service on WhatsApp was excellent." },
  { rating: 3, title: "Nice but subtle", comment: "Pretty scent but I expected slightly stronger projection. Good for daytime and office wear." },
  { rating: 5, title: "Compliment magnet", comment: "Honestly did not expect this many compliments. Elegant, warm and it lingers on my clothes." },
];

export const seedTestimonials = [
  {
    name: "Adaeze O.",
    location: "Lekki, Lagos",
    quote: "JIS is my go-to for fragrances. Everything is authentic, beautifully packaged and delivered fast. Velvet Bloom is now my signature.",
  },
  {
    name: "Tunde B.",
    location: "Wuse, Abuja",
    quote: "Ordered Noir Intense on a Monday, had it by Wednesday. The scent lasts all day and the WhatsApp support was quick and friendly.",
  },
  {
    name: "Chiamaka N.",
    location: "GRA, Port Harcourt",
    quote: "The perfume oils are incredible value. One roll of Oud Ọba in the morning and I still smell amazing at night.",
  },
];
